### PR TITLE
Update configure-node.md

### PR DESCRIPTION
**Pull request by jessicaschilling**
Incorporates changes from https://github.com/ipfs/docs/commit/7afd7f067cbaa3504da8d010b4a9b25d1aa5e793#diff-fe74492aff2b57dd7ae6c3ff9ddd9ae2
cc @johnnymatthews

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@cwaring -- I'd merge this, but am not sure what's up with the CircleCI build error situation. Can you please look when you get back from holidays? Thank you!

**Comment by Stebalien** [comment]
CircleCI isn't passing because it isn't configured. I assume we should just remove it?

**Comment by cwaring** [comment]
Heya folks, CircleCI is causing trouble here because I have enabled it as part of the IPFS hosting in ipfs/ipfs-docs-v2/pull/46 but the config is missing in this branch. Once that is merged and these PRs are rebased then there you should get the green light.

**Comment by jessicaschilling** [comment]
Figured it was something along those lines. I’ll keep an eye out, thanks!

**Pull request merged**
