### PR TITLE
Improve descriptions of academic papers

### PR DESCRIPTION
**Pull request by tniessen**
Just a few minor improvements.

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Thanks for your PR! The descriptions for each article are direct copy-and-pastes from the abstract of each paper. In the interest of consistency I'm going to leave things as they are right now.

**Comment by tniessen** [comment]
@johnnymatthews I believe that the errors I corrected were introduced by copying the text. They are not present in the original papers. Please consider reopening this PR.

**Comment by johnnymatthews** [comment]
Ah I see what you mean. Sorry for the hasty closure, I didn't notice the hyphenated fixes. I'll merge this in. Thanks for helping out with this one!

**Comment by tniessen** [comment]
Thank you! :)

**Pull request merged**
