### PR TITLE
Work on glossary.md

### PR DESCRIPTION
**Pull request by edgo914**
https://github.com/ipfs/docs/issues/56

### CODE REVIEW

**Comment by cwaring** [comment]
I had to revert this PR as there are errors that need to be corrected.

All pages need to retain the front-matter data appropriate for the page, a minimum of `title` and we shouldn't use HTML to reference anchor links. Please change all HTML tags to use [valid markdown](https://daringfireball.net/projects/markdown/syntax). e.g.

```md
[[toc]]

## A
### Announcing

## B
### Bitswap

## C
### CBOR
```

etc

`[[toc]]` will auto generate a table of contents that will stay in sync as the content changes, see - https://v1.vuepress.vuejs.org/guide/markdown.html#table-of-contents

**Comment by edgo914** [comment]
@Chris Is there an example of [[toc]] somewhere already in ipfs docs? I'm
not finding how to do this with the links provided. I'm a coder, sorry

@Johnny "any one entity" meant "any single entity, like a government or
terrorist group" ... not "anyone entity"

**Comment by johnnymatthews** [comment]
> Is there an example of [[toc]] somewhere already in ipfs docs?

@edgo914 adding a Table of Contents is as simple as adding `[[toc]]` into your markdown.

vs-code

The above example creates the ToC as seen below.

ipfs-site

---

> "any one entity" meant "any single entity, like a government or
terrorist group" ... not "anyone entity"

My bad, don't know how I missed that one. Ignore my edit then :)

**Comment by cwaring** [comment]
One thing to note is this is only a suggestion if you wish to embed the table of contents in the page itself. With the correct header levels, eg. ## for H2 and ### for H3 the sidebar will be auto populated with the section navigation. In order to disable that you would have to set `sidebarDepth: 0` in the header front matter.

I would suggest to use the automatic sidebar navigation over embedding an addition in page ToC unless the sidebar doesn't achieve the desired results. @johnnymatthews it may be best for you to experiment and advise further here.

**Comment by edgo914** [comment]
How about having the automatic sidebar navigation along with alphabet bar
at top of page? Personally, for a glossary, I like an alphabet bar and not
a ToC.

**Comment by edgo914** [comment]
Sent PR

**Comment by johnnymatthews** [comment]
I like it. Things look much cleaner, and the markdown is easier to read. This type of Table of Contents should only be used for this page though. The glossary is a special page that needs this kind of presentation.

Screenshot_2020-01-18 Glossary

I'll merge the [PR](https://github.com/ipfs/ipfs-docs-v2/pull/70) once the CI build issue is sorted.

**Pull request merged**
