### PR TITLE
Er beta styling a

### PR DESCRIPTION
**Pull request by ericronne**
With an 👁to _hopefully_ lifting some of the burden from @cwaring's shoulders, i started a branch of "barebones" css mods. I require help (or education) to complete the unchecked boxes. Thanks!

🙈= "Help wanted"

## Global
- [x] Add a lighter teal color to the palette `$accentColorLight = #b8e0e5;` 

## Site header
- [x] Increase height to `4rem`
- [x] Remove the bouncing beta hover effect ;)
- [x] Search: round the box corners, and reduce the overall width
- [x] Shift the search tool to the right
- [x] Flop the order of the GitHub link and the search box, so the search box lies to the right of all (Order: Suggest a feature  GitHub  Search)
- [x] 🙈Center the logo in mobile view:
image

## Side nav
- [x] Modify small-caps header styling for accessibility and easier scan (indent)
- [x] Make it narrower
- [x] 🙈Darken "Install IPFS" link to "black"

more to come.
closes https://github.com/ipfs/docs/issues/385

### CODE REVIEW

**Comment by ericronne** [comment]
I think this is ready for review. @cwaring if you're able to help with the two 🙈-tagged items above, that would be grand, indeed.

One note: To me, "Suggest a feature" doesn't seem to merit such high-profile treatment. It's also ambiguous: am i suggesting a docs feature or an IPFS feature?

**Comment by ericronne** [comment]
I'm going to tweak the notification badge colors, hold pls …

**Comment by ericronne** [comment]
Let's set the colors in another pr. Review away!

**Comment by cwaring** [comment]
🚢

**Pull request merged**
