### PR TITLE
Update grammar-formatting-and-style.md

### PR DESCRIPTION
**Pull request by jessicaschilling**
Broken images, broken links, copy editing for grammar, consistency, typos
fyi @johnnymatthews

### CODE REVIEW

**Comment by cwaring** [comment]
PR 💯!
Congrats you win an emoji 🎁

**Comment by johnnymatthews** [comment]
Didn't realize we had to hard link images though `raw.githubusercontent.com`. Has that always been the case, or is this a new thing?

**Comment by jessicaschilling** [comment]
It's the only way I've found to be able to reliably ensure images display in both GitHub and the rendered VuePress version.

**Comment by cwaring** [comment]
FWIW: I would favour relative links otherwise the images won't get hashed and optimised during the build pipeline and also won't be visible offline or when fetched via IPFS. Relative images _should_ display in Github too? If not we should look into that separately.

**Comment by jessicaschilling** [comment]
In the original version, the relative links displayed in GitHub, but not the VuePress version.

**Comment by johnnymatthews** [comment]
Just checking I'm on the same page here, what would a relative link look like for [line 46](https://github.com/ipfs/ipfs-docs-v2/pull/100/files#diff-6614b363b750dec52fa4be5525d63c2cR46) in this edit then? I was assuming image paths work the same way in VuePress as in other static-site generators.

Currently, the images are sitting within an `images` folder in the same directory as the page itself.

Screen Shot 2020-02-12 at 4 59 43 PM

Is this the right place, or should they be somewhere else?

**Comment by jessicaschilling** [comment]
@johnnymatthews See https://github.com/ipfs/ipfs-docs-v2/pull/110 for relative paths that work in both ... h/t @cwaring 😊

**Comment by cwaring** [comment]
both examples are valid and should work, but it the first one causes any trouble then you now have an alternative 👍

**Comment by cwaring** [comment]
relative paths keeps things IPFS and offline friendly so only use absolutes when it's absolutely necessary. this feels like another candidate for a linter rule 😅

**Pull request merged**
