### PR TITLE
Issue#93 Gateway concept doc ready for 1st review

### PR DESCRIPTION
**Pull request by EricLScace**
Ready for review. I'm sure there are some nuances not well expressed or lacking.

Open issues:
- link to instructions to set up one's own gateway
- roadmap for future evolution of gateway service(s)
- additional document links for those who wish to learn more
- final scrub for grammar and typos (I will work on this on Monday.)

### CODE REVIEW

**Comment by johnnymatthews** [comment]
This is excellent work @EricLScace! Thank you very much for your efforts here. I've made some changes to your branch directly, mainly formatting and small editorial changes. Once CI has finished testing everything I'll get this merged in and your bounty paid out.

**Comment by EricLScace** [comment]
Found and correct the error that triggered a CI check failure in https://github.com/ipfs/ipfs-docs-v2/pull/184/commits/b01f947d33d26fb49e5a04008ce3ec6aedd97fbf

**Comment by johnnymatthews** [comment]
> Found and corrected the error

@EricLScace, Nice fix!

> Sorry you had to do all that reformatting work!

@EricLScace, no problem! Check out the [contribution guidelines](https://docs-beta.ipfs.io/community/contribute/grammar-formatting-and-style/#formatting) for more info. I think that doc's _fairly_ up to date.

**Comment by johnnymatthews** [comment]
Pretty sure that failing CI build is because it won't attempt to deploy a branch by a user _outside_ of the IPFS GitHub org.

**Pull request merged**
