### PR TITLE
Updates on Bitswap and libp2p

### PR DESCRIPTION
**Pull request by edgo914**

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Ready to merge this, but just want to check with @cwaring that the failed CI deploy isn't anything too serious.

**Comment by jessicaschilling** [comment]
@johnnymatthews As far as I can see this is just the usual with contributor-provided PRs. I'd feel safe to merge; we can revert if need be.

**Comment by johnnymatthews** [comment]
Cool beans, I'll merge things in then!

**Comment by jessicaschilling** [comment]
@johnnymatthews Awesome. Can you please close https://github.com/ipfs/docs/issues/85 and https://github.com/ipfs/docs/issues/388 as appropriate, and see about getting the bounties paid out? Thanks!

**Comment by johnnymatthews** [comment]
Done and done :)

**Pull request merged**
